; SPDX-FileCopyrightText: Copyright 2024, Arm Limited and/or its affiliates.
; SPDX-License-Identifier: LicenseRef-LICENSE

; Compiler Configuration
[debug]
printIRAfterEachPass=false
printChainProposals=false
printCompiledOutput=false
printTaskSplitting=false
networkPerformanceEstimation=true
timing=false
debugDatabase=true
performanceDatabase=true
commandListSummary=true

[compiler]
enableDotDump=true
noThreads=8
disableValidation=false
shaderGenOptions=

[scheduler]
enableFusing=true
enableTensorPinning=false
enableLSpeculativeCaching=true
enableGreedyChaining=false
enableSSpeculativeCaching=true
enableSearchCascading=false
enableSearchChaining=true
enableSearchTaskSplitting=true
enableSearchWeightLooping=false
enablePairwiseStriping=true
enableDirectStriping=true
enableTosaRewrites=true
enableExternalBrickFormats=true
enableStructuredSparsity=false
enableWeightLooping=true
disableWeightEncoding=false
taskSplitEnableMinorAxis=true
taskSplitEnableAxes=1111
disableNonLocalMemoryUsage=false
disableTaskSplitAllAxes=false
disableUpscale2x2Opt=false
forceLongCascade=false

[generator]
ScLabelsMode=0
enableIRDeferredDependencies=false
enableCSDeferredDependencies=false
