# SPDX-FileCopyrightText: Copyright 2024, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

[training]
batch_size = 32
learning_rate = 1e-3
show_progress = true
steps = 48000
learning_rate_schedule = "cosine"
num_procs = 1
num_threads = 0
