# SPDX-FileCopyrightText: Copyright 2023, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: LicenseRef-LICENSE

target = "hydra"

[backend.argo]
num_npu_cores = 1

[backend.ngp-graph-compiler]
system_config = "ngp-graph-compiler/system_config_16_8x256_14.10.6.ini"
compiler_config = "ngp-graph-compiler/compiler_config.ini"
