# SPDX-FileCopyrightText: Copyright 2023, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: LicenseRef-LICENSE

target = "hydra"

[backend.ngp-graph-compiler]
system_config = "default"
compiler_config = "default"
